### ISSUE TITLE
Don't do anything on XmlHttpRequest

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/seo-override#19]
We need a way to blacklist path, url, methods...

I have some Ajax calls returning JSON in my app, and it should not fetch Seo.

BUT maybe some people load full pages in Ajax... So maybe we should check the request / response format ?

**Comment by pyrech** [comment]
We could add support for some blacklist configuration. What about something like that for the bundle configuration:

```yaml
seo_override:
    blacklist:
        - { path: "^/admin"  }
        - { method: POST  }
        - { ajax: true }
    fetchers:
        - { type: doctrine }
```

The `path` blacklist would be implemented in the `SeoManager` (and thus available for regular PHP usages).

For `method` and `ajax`, this is more the responsability of the Symfony listener because the `SeoManager` is not aware of any request's headers (only the path and the host). IMO this would probably be implemented [here](https://github.com/jolicode/seo-override/issues/19). I wonder whether we need to support blacklist configuration for response format or if hard-coding it in the listener wouldn't be enough.
